services:
  sunrise-cms:
    image: ghcr.io/sgraham3/sunrise-cms:latest
    container_name: sunrise-cms

    ports:
      - "9080:9000"

    environment:
      NODE_ENV: production
      LOGIN_USERNAME: admin
      LOGIN_PASSWORD: admin

    volumes:
      - ./data:/app/data
      - ./database:/app/database
      - ./downloads:/app/downloads

    shm_size: '2gb'

    restart: unless-stopped
